#!/bin/sh

cp -a localenv-conf /usr/bin/
cp -a localenv-discover /usr/bin/
cp -a localenv-scripts /usr/bin/
cp -ar localenv.d-skel /etc/localenv.d 

chown -R root:root /usr/bin/localenv-conf
chown -R root:root /usr/bin/localenv-discover
chown -R root:root /usr/bin/localenv-scripts
chown -R root:root /etc/localenv.d 

