#!/bin/sh
#
#  localenv-confs
#
#  Parse confs in /dir/[profile]/confs/ and replace system confs with
#  the parsed confs.
#

function usage() {
	echo "Usage: $0 PROFILE PATH"
	echo "Run scripts in [path]/[profile]/scripts/ in the correct order."
	echo
	echo "Options:"
	echo "  None"
	echo
}

function msg() {
	if [ -n "$FLAG_VERBOSE" ]; then
		echo "$*" >&2
	fi
}

function handle_cmdline() {
	TEMP=`getopt -o hdvp: --long dry-run,profile,help,verbose -n 'localenv-scripts' -- "$@"`

	if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

	eval set -- "$TEMP"

	while true ; do
		case "$1" in
			-d|--dry-run)  DRY_RUN=1;      shift 1;;
			-p|--profile)  PROFILE=$2;     shift 2;;
			-h|--help)     FLAG_HELP=1;    shift 1;;
			-v|--verbose)  FLAG_VERBOSE=1; shift 1;;
			--)                            shift 1; break;;
			*)             echo "Internal error!" ; exit 1;;
		esac
	done

	if [ $# -ne 2 ]; then
		FLAG_HELP=1
	fi

	if [ "$FLAG_HELP" ]; then
		usage
		exit
	fi

	PROFILE=$1
	SCR_PATH=$2

	if [ ! "$PROFILE" ]; then
		usage
		exit
	fi

	if [ ! -d "$SCR_PATH/$PROFILE/scripts/" ]; then
		echo "No configurations found for profile '$PROFILE' in $SCR_PATH/$PROFILE/confs/" >&2
		exit
	fi
}

handle_cmdline $*

for CONF in `ls "$SCR_PATH/$PROFILE/confs/" | sort -n`; do
	cat $SCR_PATH/$PROFILE/confs/$CONF | while read LINE; do
		if [ ! "$STARTED" ]; then
			# Still working on the header of the conf file
			if [ ! "$LINE" == "--" ]; then
				# Key value line
				KEY=`echo "$LINE" | cut -d"=" -f1`
				VALUE=`echo "$LINE" | cut -d"=" -f2`

				if [ "$KEY" == "dest" ]; then
					DEST=$VALUE
				elif [ "$KEY" == "mode" ]; then
					MODE=$VALUE
				fi
			fi
		else
			# Copy or append the config to DEST
			echo $LINE >> $DEST
		fi

		if [ "$LINE" == "--" ]; then
			# We've reached the real config. Start copying or appending it
			STARTED=1
			if [ "$MODE" == "overwrite" ]; then
				> "$DEST"
			fi
		fi

	done
done
